name: first workflow
on:
  push:
jobs:
 build:
  runs-on : ubuntu-latest
  steps:
    - name : checkout code
      uses : action/checkout@v4
    - name : print build started
      run : echo "build started"
